server:
  port: ${PAYMENT_PORT:8094}

spring:
  application:
    name: payment-service

  security:
    oauth2:
      resourceserver:
        jwt:
          secret: ${JWT_SECRET}
  datasource:
    url: ${DB_PAYMENT_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://discovery-service:8761/eureka/}
    register-with-eureka: true
    fetch-registry: true

jwt:
  secret: ${JWT_SECRET}



momo:
  partner-code: ${MOMO_PARTNER_CODE}
  access-key: ${MOMO_ACCESS_KEY}
  secret-key: ${MOMO_SECRET_KEY}
  endpoint: https://test-payment.momo.vn/v2/gateway/api/create
  redirect-url: ${MOMO_REDIRECT_URL:http://localhost:3000/recruiter/payment-return}
  ipn-url: ${MOMO_IPN_URL:http://localhost:8094/api/payment/momo-callback}

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
    iuh.fit.se.payment_service: DEBUG