server:
  port: ${EMPLOYER_PORT:8086}

spring:
  application:
    name: employer-service

  datasource:
    url: ${DB_EMPLOYER_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://discovery-service:8761/eureka/}
    register-with-eureka: true
    fetch-registry: true

jwt:
  secret: ${JWT_SECRET}

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
    feign.client: DEBUG
    iuh.fit.se.employer_service.client.AuthServiceClient: DEBUG
    iuh.fit.se.employer_service: DEBUG