server:
  port: ${STORAGE_PORT:8083}

spring:
  application:
    name: storage-service
  security:
    oauth2:
      resourceserver:
        jwt:
          secret: ${JWT_SECRET}

  datasource:
    url: ${DB_STORAGE_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://discovery-service:8761/eureka/}
    register-with-eureka: true
    fetch-registry: true

jwt:
  secret: ${JWT_SECRET}



file:
  upload-dir: ${FILE_UPLOAD_DIR:./uploads}

minio:
  url: ${MINIO_URL:http://minio:9000}
  access-key: ${MINIO_ACCESS_KEY:minioadmin}
  secret-key: ${MINIO_SECRET_KEY:minioadmin}
  bucket: ${MINIO_BUCKET:storage-files}

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
    iuh.fit.se.storage_service: DEBUG