server:
  port: ${CHATBOT_PORT:8089}

# Gemini AI
gemini:
  api:
    key: ${GEMINI_API_KEY}

# Database
spring:
  application:
    name: chatbot-service
  security:
    oauth2:
      resourceserver:
        jwt:
          secret: ${JWT_SECRET}
  datasource:
    url: ${DB_CHATBOT_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect

# Eureka
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://discovery-service:8761/eureka/}
    register-with-eureka: true
    fetch-registry: true

# JWT
jwt:
  secret: ${JWT_SECRET}
  access:
    expiration: 3600000
  refresh:
    expiration: 604800000



# Logging
logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
    iuh.fit.se.chatbot_service: DEBUG