server:
  port: ${JOB_PORT:8084}

spring:
  application:
    name: job-service

  devtools:
    restart:
      enabled: false
    livereload:
      enabled: false

  datasource:
    url: ${DB_JOB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:kafka:9092}
    consumer:
      group-id: ${KAFKA_GROUP_ID:job-group}
      auto-offset-reset: ${KAFKA_AUTO_OFFSET_RESET:earliest}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://discovery-service:8761/eureka/}
    register-with-eureka: true
    fetch-registry: true

jwt:
  secret: ${JWT_SECRET}

kafka:
  enabled: ${KAFKA_ENABLED:false}

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
    iuh.fit.se.job_service: DEBUG

feign:
  client:
    config:
      default:
        loggerLevel: full

